name: Docker Image Eafy App

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKERPW: ${{ secrets.DOCKERPW }}
      run: echo "${{ secrets.DOCKERPW }}" | docker login -u "gmowilliams" --password-stdin
    - name: Run Docker Compose
      run: docker compose up
    - name: Docker Push
      run: docker push gmowilliams/eafy_solutions:1.0.0
      
